//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMainService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeMainService.IEmployeeService")]
    public interface IEmployeeService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetData", ReplyAction="http://tempuri.org/IEmployeeService/GetDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployeeMainService.GetDataResponse> GetDataAsync(EmployeeMainService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AddEmployyeeRecord", ReplyAction="http://tempuri.org/IEmployeeService/AddEmployyeeRecordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployeeMainService.AddEmployyeeRecordResponse> AddEmployyeeRecordAsync(EmployeeMainService.AddEmployyeeRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeRecords", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeRecordsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployeeMainService.GetEmployeeRecordsResponse> GetEmployeeRecordsAsync(EmployeeMainService.GetEmployeeRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/DeleteRecords", ReplyAction="http://tempuri.org/IEmployeeService/DeleteRecordsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployeeMainService.DeleteRecordsResponse> DeleteRecordsAsync(EmployeeMainService.DeleteRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/SearchEmployeeRecord", ReplyAction="http://tempuri.org/IEmployeeService/SearchEmployeeRecordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployeeMainService.SearchEmployeeRecordResponse> SearchEmployeeRecordAsync(EmployeeMainService.SearchEmployeeRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/UpdateEmployeeContact", ReplyAction="http://tempuri.org/IEmployeeService/UpdateEmployeeContactResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmployeeMainService.UpdateEmployeeContactResponse> UpdateEmployeeContactAsync(EmployeeMainService.UpdateEmployeeContactRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest()
        {
        }
        
        public GetDataRequest(int value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDataResult;
        
        public GetDataResponse()
        {
        }
        
        public GetDataResponse(string GetDataResult)
        {
            this.GetDataResult = GetDataResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/EmployeeServices")]
    public partial class Employee
    {
        
        private string emailField;
        
        private string empIDField;
        
        private string genderField;
        
        private string nameField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string EmpID
        {
            get
            {
                return this.empIDField;
            }
            set
            {
                this.empIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddEmployyeeRecord", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddEmployyeeRecordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EmployeeMainService.Employee emp;
        
        public AddEmployyeeRecordRequest()
        {
        }
        
        public AddEmployyeeRecordRequest(EmployeeMainService.Employee emp)
        {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddEmployyeeRecordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddEmployyeeRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddEmployyeeRecordResult;
        
        public AddEmployyeeRecordResponse()
        {
        }
        
        public AddEmployyeeRecordResponse(string AddEmployyeeRecordResult)
        {
            this.AddEmployyeeRecordResult = AddEmployyeeRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmployeeRecordsRequest
    {
        
        public GetEmployeeRecordsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmployeeRecordsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EmployeeMainService.ArrayOfXElement GetEmployeeRecordsResult;
        
        public GetEmployeeRecordsResponse()
        {
        }
        
        public GetEmployeeRecordsResponse(EmployeeMainService.ArrayOfXElement GetEmployeeRecordsResult)
        {
            this.GetEmployeeRecordsResult = GetEmployeeRecordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRecordsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EmployeeMainService.Employee emp;
        
        public DeleteRecordsRequest()
        {
        }
        
        public DeleteRecordsRequest(EmployeeMainService.Employee emp)
        {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRecordsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeleteRecordsResult;
        
        public DeleteRecordsResponse()
        {
        }
        
        public DeleteRecordsResponse(string DeleteRecordsResult)
        {
            this.DeleteRecordsResult = DeleteRecordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchEmployeeRecord", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchEmployeeRecordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EmployeeMainService.Employee emp;
        
        public SearchEmployeeRecordRequest()
        {
        }
        
        public SearchEmployeeRecordRequest(EmployeeMainService.Employee emp)
        {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchEmployeeRecordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchEmployeeRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EmployeeMainService.ArrayOfXElement SearchEmployeeRecordResult;
        
        public SearchEmployeeRecordResponse()
        {
        }
        
        public SearchEmployeeRecordResponse(EmployeeMainService.ArrayOfXElement SearchEmployeeRecordResult)
        {
            this.SearchEmployeeRecordResult = SearchEmployeeRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEmployeeContact", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateEmployeeContactRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EmployeeMainService.Employee emp;
        
        public UpdateEmployeeContactRequest()
        {
        }
        
        public UpdateEmployeeContactRequest(EmployeeMainService.Employee emp)
        {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEmployeeContactResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateEmployeeContactResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UpdateEmployeeContactResult;
        
        public UpdateEmployeeContactResponse()
        {
        }
        
        public UpdateEmployeeContactResponse(string UpdateEmployeeContactResult)
        {
            this.UpdateEmployeeContactResult = UpdateEmployeeContactResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IEmployeeServiceChannel : EmployeeMainService.IEmployeeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<EmployeeMainService.IEmployeeService>, EmployeeMainService.IEmployeeService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EmployeeServiceClient() : 
                base(EmployeeServiceClient.GetDefaultBinding(), EmployeeServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEmployeeService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployeeServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EmployeeServiceClient.GetBindingForEndpoint(endpointConfiguration), EmployeeServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployeeServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmployeeServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployeeServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EmployeeServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeMainService.GetDataResponse> EmployeeMainService.IEmployeeService.GetDataAsync(EmployeeMainService.GetDataRequest request)
        {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeMainService.GetDataResponse> GetDataAsync(int value)
        {
            EmployeeMainService.GetDataRequest inValue = new EmployeeMainService.GetDataRequest();
            inValue.value = value;
            return ((EmployeeMainService.IEmployeeService)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeMainService.AddEmployyeeRecordResponse> EmployeeMainService.IEmployeeService.AddEmployyeeRecordAsync(EmployeeMainService.AddEmployyeeRecordRequest request)
        {
            return base.Channel.AddEmployyeeRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeMainService.AddEmployyeeRecordResponse> AddEmployyeeRecordAsync(EmployeeMainService.Employee emp)
        {
            EmployeeMainService.AddEmployyeeRecordRequest inValue = new EmployeeMainService.AddEmployyeeRecordRequest();
            inValue.emp = emp;
            return ((EmployeeMainService.IEmployeeService)(this)).AddEmployyeeRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeMainService.GetEmployeeRecordsResponse> EmployeeMainService.IEmployeeService.GetEmployeeRecordsAsync(EmployeeMainService.GetEmployeeRecordsRequest request)
        {
            return base.Channel.GetEmployeeRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeMainService.GetEmployeeRecordsResponse> GetEmployeeRecordsAsync()
        {
            EmployeeMainService.GetEmployeeRecordsRequest inValue = new EmployeeMainService.GetEmployeeRecordsRequest();
            return ((EmployeeMainService.IEmployeeService)(this)).GetEmployeeRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeMainService.DeleteRecordsResponse> EmployeeMainService.IEmployeeService.DeleteRecordsAsync(EmployeeMainService.DeleteRecordsRequest request)
        {
            return base.Channel.DeleteRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeMainService.DeleteRecordsResponse> DeleteRecordsAsync(EmployeeMainService.Employee emp)
        {
            EmployeeMainService.DeleteRecordsRequest inValue = new EmployeeMainService.DeleteRecordsRequest();
            inValue.emp = emp;
            return ((EmployeeMainService.IEmployeeService)(this)).DeleteRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeMainService.SearchEmployeeRecordResponse> EmployeeMainService.IEmployeeService.SearchEmployeeRecordAsync(EmployeeMainService.SearchEmployeeRecordRequest request)
        {
            return base.Channel.SearchEmployeeRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeMainService.SearchEmployeeRecordResponse> SearchEmployeeRecordAsync(EmployeeMainService.Employee emp)
        {
            EmployeeMainService.SearchEmployeeRecordRequest inValue = new EmployeeMainService.SearchEmployeeRecordRequest();
            inValue.emp = emp;
            return ((EmployeeMainService.IEmployeeService)(this)).SearchEmployeeRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeMainService.UpdateEmployeeContactResponse> EmployeeMainService.IEmployeeService.UpdateEmployeeContactAsync(EmployeeMainService.UpdateEmployeeContactRequest request)
        {
            return base.Channel.UpdateEmployeeContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeMainService.UpdateEmployeeContactResponse> UpdateEmployeeContactAsync(EmployeeMainService.Employee emp)
        {
            EmployeeMainService.UpdateEmployeeContactRequest inValue = new EmployeeMainService.UpdateEmployeeContactRequest();
            inValue.emp = emp;
            return ((EmployeeMainService.IEmployeeService)(this)).UpdateEmployeeContactAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEmployeeService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEmployeeService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:58257/EmpService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EmployeeServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEmployeeService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EmployeeServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEmployeeService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEmployeeService,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
